-- Create database and tables for WebLab admin
CREATE DATABASE IF NOT EXISTS weblab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE weblab;

-- NEWS posts
CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  cover VARCHAR(255) DEFAULT NULL,
  is_published TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TEAM members
CREATE TABLE IF NOT EXISTS team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(120) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  visible TINYINT(1) DEFAULT 1,
  sort_no INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
